export const availableTags = [
    'fundamentals',
    'course',
    'exercise',
    'supplement',
    'reference',
    'advanced',
    'beginner',
    'matlab',
    'python',
    'lab',
    'theory',
    'practical',
    'audio',
    'biomedical',
    'communication',
    'image',
    'radar',
    'sensors',
    'speech',
    'wireless',
    'fourier',
    'filtering',
    'sampling',
    'transform',
    'spectral',
    'adaptive',
    'tutorial',
    'software',
    'tools',
    'programming',
    'simulation',
];

export const availableFields = [
    'Signal Processing',
    'Digital Communications',
    'Biomedical Engineering',
    'Audio Processing',
    'Image Processing',
    'Radar Systems',
    'Machine Learning',
    'Software Development',
    'Mathematics',
    'Programming',
];

export const availableTypes = [
    'Exercises',
    'Book',
    'Sheet',
    'Paper',
    'Notes',
    'Video',
    'Playlist',
    'Software',
    'Tool',
];
